language: php

php:
  - "5.4"
  - "5.5"
  - "5.6"
  - "hhvm"

matrix:
  allow_failures:
    - php: hhvm

install:
  - composer install --prefer-dist --dev --no-progress --optimize-autoloader

script: vendor/bin/phpunit --coverage-text
